version: '3.7'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=nest
    ports:
      - "5432:5432"
    expose:
      - "5432"
  rest:
    build: .
    ports:
      - "3000:3000"
    links:
      - db
    expose:
      - "3000"

